const AuthActionTypes = {
    CONVERSATION_ADD_START: "CONVERSATION_ADD_START",
    CONVERSATION_ADD_SUCCESS: "CONVERSATION_ADD_SUCCESS",
    CONVERSATION_ADD_FAILURE: "CONVERSATION_ADD_FAILURE",

    CONVERSATION_GET_PRIVATE_BY_ID_START: "CONVERSATION_GET_PRIVATE_BY_ID_START",
    CONVERSATION_GET_PRIVATE_BY_ID_SUCCESS: "CONVERSATION_GET_PRIVATE_BY_ID_SUCCESS",
    CONVERSATION_GET_PRIVATE_BY_ID_FAILURE: "CONVERSATION_GET_PRIVATE_BY_ID_FAILURE",

    CONVERSATION_GET_GROUP_BY_ID_START: "CONVERSATION_GET_GROUP_BY_ID_START",
    CONVERSATION_GET_GROUP_BY_ID_SUCCESS: "CONVERSATION_GET_GROUP_BY_ID_SUCCESS",
    CONVERSATION_GET_GROUP_BY_ID_FAILURE: "CONVERSATION_GET_GROUP_BY_ID_FAILURE",

    CONVERSATION_GET_USERS_ALL_PRIVATE_START: "CONVERSATION_GET_USERS_ALL_PRIVATE_START",
    CONVERSATION_GET_USERS_ALL_PRIVATE_SUCCESS: "CONVERSATION_GET_USERS_ALL_PRIVATE_SUCCESS",
    CONVERSATION_GET_USERS_ALL_PRIVATE_FAILURE: "CONVERSATION_GET_USERS_ALL_PRIVATE_FAILURE",

    CONVERSATION_GET_USERS_ALL_GROUP_START: "CONVERSATION_GET_USERS_ALL_GROUP_START",
    CONVERSATION_GET_USERS_ALL_GROUP_SUCCESS: "CONVERSATION_GET_USERS_ALL_GROUP_SUCCESS",
    CONVERSATION_GET_USERS_ALL_GROUP_FAILURE: "CONVERSATION_GET_USERS_ALL_GROUP_FAILURE",

    CONVERSATION_ADD_LAST_MESSAGE_START: "CONVERSATION_ADD_LAST_MESSAGE_START",
    CONVERSATION_ADD_LAST_MESSAGE_SUCCESS: "CONVERSATION_ADD_LAST_MESSAGE_SUCCESS",
    CONVERSATION_ADD_LAST_MESSAGE_FAILURE: "CONVERSATION_ADD_LAST_MESSAGE_FAILURE",

    CONVERSATION_LEAVE_A_GROUP_START: "CONVERSATION_LEAVE_A_GROUP_START",
    CONVERSATION_LEAVE_A_GROUP_SUCCESS: "CONVERSATION_LEAVE_A_GROUP_SUCCESS",
    CONVERSATION_LEAVE_A_GROUP_FAILURE: "CONVERSATION_LEAVE_A_GROUP_FAILURE",

    CONVERSATION_ADD_PEOPLE_TO_THE_GROUP_START: "CONVERSATION_ADD_PEOPLE_TO_THE_GROUP_START",
    CONVERSATION_ADD_PEOPLE_TO_THE_GROUP_SUCCESS: "CONVERSATION_ADD_PEOPLE_TO_THE_GROUP_SUCCESS",
    CONVERSATION_ADD_PEOPLE_TO_THE_GROUP_FAILURE: "CONVERSATION_ADD_PEOPLE_TO_THE_GROUP_FAILURE",
}

export default AuthActionTypes;