const AuthActionTypes = {
    CONVERSATION_ADD_START: "CONVERSATION_ADD_START",
    CONVERSATION_ADD_SUCCESS: "CONVERSATION_ADD_SUCCESS",
    CONVERSATION_ADD_FAILURE: "CONVERSATION_ADD_FAILURE",

    CONVERSATION_GET_PRIVATE_BY_ID_START: "CONVERSATION_GET_PRIVATE_BY_ID_START",
    CONVERSATION_GET_PRIVATE_BY_ID_SUCCESS: "CONVERSATION_GET_PRIVATE_BY_ID_SUCCESS",
    CONVERSATION_GET_PRIVATE_BY_ID_FAILURE: "CONVERSATION_GET_PRIVATE_BY_ID_FAILURE",

    CONVERSATION_GET_GROUP_BY_ID_START: "CONVERSATION_GET_GROUP_BY_ID_START",
    CONVERSATION_GET_GROUP_BY_ID_SUCCESS: "CONVERSATION_GET_GROUP_BY_ID_SUCCESS",
    CONVERSATION_GET_GROUP_BY_ID_FAILURE: "CONVERSATION_GET_GROUP_BY_ID_FAILURE",

    AUTH_LOGOUT_START: "AUTH_LOGOUT_START",
    AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
    AUTH_LOGOUT_FAILURE: "AUTH_LOGOUT_FAILURE",
}

export default AuthActionTypes;