const MessageActionTypes = {
    MESSAGE_GET_GROUPS_ALL_MESSAGES_START: "MESSAGE_GET_GROUPS_ALL_MESSAGES_START",
    MESSAGE_GET_GROUPS_ALL_MESSAGES_SUCCESS: "MESSAGE_GET_GROUPS_ALL_MESSAGES_SUCCESS",
    MESSAGE_GET_GROUPS_ALL_MESSAGES_FAILURE: "MESSAGE_GET_GROUPS_ALL_MESSAGES_FAILURE"
}

export default MessageActionTypes;