const AuthActionTypes = {
    AUTH_REGISTER_START: "AUTH_REGISTER_START",
    AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
    AUTH_REGISTER_FAILURE: "AUTH_REGISTER_FAILURE",

    AUTH_LOGIN_START: "AUTH_LOGIN_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",

    AUTH_LOGOUT_START: "AUTH_LOGOUT_START",
    AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
    AUTH_LOGOUT_FAILURE: "AUTH_LOGOUT_FAILURE",
}

export default AuthActionTypes;